### ISSUE TITLE
C code fails to compile on MacOSX Arm64

### ISSUE THREAD

**Issue by billbrod** [LabForComputationalVision/pyrtools#21]
Copied from [plenoptic](https://github.com/LabForComputationalVision/plenoptic/issues/194), since this is a pyrtools issue.

**Describe the bug**
Failure to import on MacOSX Arm64, either installed via git clone ... ; pip install -e .

**Log**

```
import plenoptic as po
Traceback (most recent call last):
  File "/Users/user/mambaforge/envs/XXX/lib/python3.10/site-packages/IPython/core/interactiveshell.py", line 3442, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-2-31aae8407192>", line 1, in <module>
    import plenoptic as po
  File "/Users/user/Library/Application Support/JetBrains/Toolbox/apps/PyCharm-P/ch-0/223.8617.48/PyCharm.app/Contents/plugins/python/helpers/pydev/_pydev_bundle/pydev_import_hook.py", line 21, in do_import
    module = self._system_import(name, *args, **kwargs)
  File "/Users/user/PycharmProjects/XXX/plenoptic/plenoptic/__init__.py", line 1, in <module>
    from . import simulate as simul
  File "/Users/user/Library/Application Support/JetBrains/Toolbox/apps/PyCharm-P/ch-0/223.8617.48/PyCharm.app/Contents/plugins/python/helpers/pydev/_pydev_bundle/pydev_import_hook.py", line 21, in do_import
    module = self._system_import(name, *args, **kwargs)
  File "/Users/user/PycharmProjects/XXX/plenoptic/plenoptic/simulate/__init__.py", line 1, in <module>
    from .models import *
  File "/Users/user/Library/Application Support/JetBrains/Toolbox/apps/PyCharm-P/ch-0/223.8617.48/PyCharm.app/Contents/plugins/python/helpers/pydev/_pydev_bundle/pydev_import_hook.py", line 21, in do_import
    module = self._system_import(name, *args, **kwargs)
  File "/Users/user/PycharmProjects/XXX/plenoptic/plenoptic/simulate/models/__init__.py", line 1, in <module>
    from .frontend import *
  File "/Users/user/Library/Application Support/JetBrains/Toolbox/apps/PyCharm-P/ch-0/223.8617.48/PyCharm.app/Contents/plugins/python/helpers/pydev/_pydev_bundle/pydev_import_hook.py", line 21, in do_import
    module = self._system_import(name, *args, **kwargs)
  File "/Users/user/PycharmProjects/XXX/plenoptic/plenoptic/simulate/models/frontend.py", line 20, in <module>
    from .naive import Gaussian, CenterSurround
  File "/Users/user/Library/Application Support/JetBrains/Toolbox/apps/PyCharm-P/ch-0/223.8617.48/PyCharm.app/Contents/plugins/python/helpers/pydev/_pydev_bundle/pydev_import_hook.py", line 21, in do_import
    module = self._system_import(name, *args, **kwargs)
  File "/Users/user/PycharmProjects/XXX/plenoptic/plenoptic/simulate/models/naive.py", line 8, in <module>
    from plenoptic.tools.conv import same_padding
  File "/Users/user/Library/Application Support/JetBrains/Toolbox/apps/PyCharm-P/ch-0/223.8617.48/PyCharm.app/Contents/plugins/python/helpers/pydev/_pydev_bundle/pydev_import_hook.py", line 21, in do_import
    module = self._system_import(name, *args, **kwargs)
  File "/Users/user/PycharmProjects/XXX/plenoptic/plenoptic/tools/__init__.py", line 1, in <module>
    from .data import *
  File "/Users/user/Library/Application Support/JetBrains/Toolbox/apps/PyCharm-P/ch-0/223.8617.48/PyCharm.app/Contents/plugins/python/helpers/pydev/_pydev_bundle/pydev_import_hook.py", line 21, in do_import
    module = self._system_import(name, *args, **kwargs)
  File "/Users/user/PycharmProjects/XXX/plenoptic/plenoptic/tools/data.py", line 8, in <module>
    from pyrtools import synthetic_images
  File "/Users/user/Library/Application Support/JetBrains/Toolbox/apps/PyCharm-P/ch-0/223.8617.48/PyCharm.app/Contents/plugins/python/helpers/pydev/_pydev_bundle/pydev_import_hook.py", line 21, in do_import
    module = self._system_import(name, *args, **kwargs)
  File "/Users/user/mambaforge/envs/XXX/lib/python3.10/site-packages/pyrtools/__init__.py", line 1, in <module>
    from . import pyramids
  File "/Users/user/Library/Application Support/JetBrains/Toolbox/apps/PyCharm-P/ch-0/223.8617.48/PyCharm.app/Contents/plugins/python/helpers/pydev/_pydev_bundle/pydev_import_hook.py", line 21, in do_import
    module = self._system_import(name, *args, **kwargs)
  File "/Users/user/mambaforge/envs/XXX/lib/python3.10/site-packages/pyrtools/pyramids/__init__.py", line 1, in <module>
    from .GaussianPyramid import GaussianPyramid
  File "/Users/user/Library/Application Support/JetBrains/Toolbox/apps/PyCharm-P/ch-0/223.8617.48/PyCharm.app/Contents/plugins/python/helpers/pydev/_pydev_bundle/pydev_import_hook.py", line 21, in do_import
    module = self._system_import(name, *args, **kwargs)
  File "/Users/user/mambaforge/envs/XXX/lib/python3.10/site-packages/pyrtools/pyramids/GaussianPyramid.py", line 3, in <module>
    from .c.wrapper import corrDn
  File "/Users/user/Library/Application Support/JetBrains/Toolbox/apps/PyCharm-P/ch-0/223.8617.48/PyCharm.app/Contents/plugins/python/helpers/pydev/_pydev_bundle/pydev_import_hook.py", line 21, in do_import
    module = self._system_import(name, *args, **kwargs)
  File "/Users/user/mambaforge/envs/XXX/lib/python3.10/site-packages/pyrtools/pyramids/c/wrapper.py", line 17, in <module>
    lib = ctypes.cdll.LoadLibrary(libpath[0])
  File "/Users/user/mambaforge/envs/XXX/lib/python3.10/ctypes/__init__.py", line 452, in LoadLibrary
    return self._dlltype(name)
  File "/Users/user/mambaforge/envs/XXX/lib/python3.10/ctypes/__init__.py", line 374, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: dlopen(/Users/user/mambaforge/envs/XXX/lib/python3.10/site-packages/pyrtools/pyramids/c/wrapConv.cpython-310-darwin.so, 0x0006): tried: '/Users/user/mambaforge/envs/XXX/lib/python3.10/site-packages/pyrtools/pyramids/c/wrapConv.cpython-310-darwin.so' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64')), '/System/Volumes/Preboot/Cryptexes/OS/Users/user/mambaforge/envs/XXX/lib/python3.10/site-packages/pyrtools/pyramids/c/wrapConv.cpython-310-darwin.so' (no such file), '/Users/user/mambaforge/envs/XXX/lib/python3.10/site-packages/pyrtools/pyramids/c/wrapConv.cpython-310-darwin.so' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64'))
```
**System (please complete the following information):**

    OS: MacOS 13.2 Ventura (M1 Max chip)
    Python 3.10 (Mambaforge)

**Additional context**
Can possibly be remedied using certain tricks, e.g. https://apple.stackexchange.com/questions/436801/m1-mac-mach-o-file-but-is-an-incompatible-architecture-have-x86-64-need-a

This issue seems to be primarily with pyrtools

After installing pyrtools in a new environment: `python -c "import pyrtools as pt" 2> pyrtools.log`

```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Users/user/mambaforge/envs/pyrtools_test/lib/python3.10/site-packages/pyrtools/__init__.py", line 1, in <module>
    from . import pyramids
  File "/Users/user/mambaforge/envs/pyrtools_test/lib/python3.10/site-packages/pyrtools/pyramids/__init__.py", line 1, in <module>
    from .GaussianPyramid import GaussianPyramid
  File "/Users/user/mambaforge/envs/pyrtools_test/lib/python3.10/site-packages/pyrtools/pyramids/GaussianPyramid.py", line 3, in <module>
    from .c.wrapper import corrDn
  File "/Users/user/mambaforge/envs/pyrtools_test/lib/python3.10/site-packages/pyrtools/pyramids/c/wrapper.py", line 17, in <module>
    lib = ctypes.cdll.LoadLibrary(libpath[0])
  File "/Users/user/mambaforge/envs/pyrtools_test/lib/python3.10/ctypes/__init__.py", line 452, in LoadLibrary
    return self._dlltype(name)
  File "/Users/user/mambaforge/envs/pyrtools_test/lib/python3.10/ctypes/__init__.py", line 374, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: dlopen(/Users/user/mambaforge/envs/pyrtools_test/lib/python3.10/site-packages/pyrtools/pyramids/c/wrapConv.cpython-310-darwin.so, 0x0006): tried: '/Users/user/mambaforge/envs/pyrtools_test/lib/python3.10/site-packages/pyrtools/pyramids/c/wrapConv.cpython-310-darwin.so' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64')), '/System/Volumes/Preboot/Cryptexes/OS/Users/user/mambaforge/envs/pyrtools_test/lib/python3.10/site-packages/pyrtools/pyramids/c/wrapConv.cpython-310-darwin.so' (no such file), '/Users/user/mambaforge/envs/pyrtools_test/lib/python3.10/site-packages/pyrtools/pyramids/c/wrapConv.cpython-310-darwin.so' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64'))
```

**Comment by billbrod** [comment]
I'm trying to find a MacOS device with Arm64 to test on, but for now: @ oren-weiss  did you try adding the `--no-binary` flag to pip when installing pyrtools, like that stack exchange post suggested? Did anything change?

**Comment by billbrod** [comment]
And do you get anything suspicious output when you run `pip install pyrtools`, or does it look like it completes without any problems?

**Comment by oren-weiss** [comment]
So I feel dumb, but yes that does appear to have fixed it, very simple.  

For completeness, there was no error when installing normally: ```
>pip install pyrtools
pip install pyrtools                                          02/06/2023 05:49:16 PM
Collecting pyrtools
  Using cached pyrtools-1.0.1-cp310-cp310-macosx_11_0_arm64.whl
Collecting Pillow>=3.4
  Using cached Pillow-9.4.0-cp310-cp310-macosx_11_0_arm64.whl (3.0 MB)
Collecting matplotlib>=1.5
  Using cached matplotlib-3.6.3-cp310-cp310-macosx_11_0_arm64.whl (7.2 MB)
Collecting tqdm>=4.29
  Using cached tqdm-4.64.1-py2.py3-none-any.whl (78 kB)
Collecting numpy>=1.1
  Using cached numpy-1.24.2-cp310-cp310-macosx_11_0_arm64.whl (13.9 MB)
Collecting scipy>=0.18
  Using cached scipy-1.10.0-cp310-cp310-macosx_12_0_arm64.whl (28.8 MB)
Collecting requests>=2.21
  Using cached requests-2.28.2-py3-none-any.whl (62 kB)
Collecting fonttools>=4.22.0
  Using cached fonttools-4.38.0-py3-none-any.whl (965 kB)
Collecting packaging>=20.0
  Using cached packaging-23.0-py3-none-any.whl (42 kB)
Collecting python-dateutil>=2.7
  Using cached python_dateutil-2.8.2-py2.py3-none-any.whl (247 kB)
Collecting pyparsing>=2.2.1
  Using cached pyparsing-3.0.9-py3-none-any.whl (98 kB)
Collecting kiwisolver>=1.0.1
  Using cached kiwisolver-1.4.4-cp310-cp310-macosx_11_0_arm64.whl (63 kB)
Collecting contourpy>=1.0.1
  Using cached contourpy-1.0.7-cp310-cp310-macosx_11_0_arm64.whl (229 kB)
Collecting cycler>=0.10
  Using cached cycler-0.11.0-py3-none-any.whl (6.4 kB)
Collecting urllib3<1.27,>=1.21.1
  Using cached urllib3-1.26.14-py2.py3-none-any.whl (140 kB)
Collecting certifi>=2017.4.17
  Using cached certifi-2022.12.7-py3-none-any.whl (155 kB)
Collecting charset-normalizer<4,>=2
  Using cached charset_normalizer-3.0.1-cp310-cp310-macosx_11_0_arm64.whl (122 kB)
Collecting idna<4,>=2.5
  Using cached idna-3.4-py3-none-any.whl (61 kB)
Collecting six>=1.5
  Using cached six-1.16.0-py2.py3-none-any.whl (11 kB)
Installing collected packages: charset-normalizer, urllib3, tqdm, six, pyparsing, Pillow, packaging, numpy, kiwisolver, idna, fonttools, cycler, certifi, scipy, requests, python-dateutil, contourpy, matplotlib, pyrtools
Successfully installed Pillow-9.4.0 certifi-2022.12.7 charset-normalizer-3.0.1 contourpy-1.0.7 cycler-0.11.0 fonttools-4.38.0 idna-3.4 kiwisolver-1.4.4 matplotlib-3.6.3 numpy-1.24.2 packaging-23.0 pyparsing-3.0.9 pyrtools-1.0.1 python-dateutil-2.8.2 requests-2.28.2 scipy-1.10.0 six-1.16.0 tqdm-4.64.1 urllib3-1.26.14
```

**Comment by billbrod** [comment]
Huh, odd. I would not have guessed that would help (because it [doesn't look like](https://pypi.org/project/pyrtools/#files) we have any pre-built binaries on PyPI), but glad that fixed it! I'm going to close this now, we can re-open it if necessary.

(If you install `plenoptic` in the environment with the working `pyrtools`, everything should work, follow up on your original issue if not)
